name: Update hosts

on:
  push:
    paths:
      - 'setHosts.py'
      - 'setHosts_Classic.py'
      - 'requirements.txt'
    branches:
      - 'master'
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-hosts:
    runs-on: ubuntu-latest
    
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo pip install -r requirements.txt
      
      - name: Install pycodestyle
        run: pip install pycodestyle
      - name: Run pycodestyle
        id: pycodestyle
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' | xargs pycodestyle --statistics > pep8_issues.txt || true
      - name: Read pycodestyle output
        id: read_pep8_issues
        run: echo "::set-output name=pep8_issues::$(cat pep8_issues.txt)"

      - name: Run hosts update script1
        run: | 
          sudo python3 setHosts.py
      
      # 提交并推送更新（仅在文件变更时）
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update hosts list"
          add: |
            hosts
            README.md
          push: true